kfs_gripper_rotate:
  ros__parameters:
    command_topic: /r2/gripper/rotate_cmd
    feedback_topic: /r2/gripper/rotate_feedback
    service_name: /r2/gripper/set_rotate
    default_tolerance: 0.01
    default_timeout_sec: 10.0
