/robot_r2_gripper:
  ros__parameters:
    gripper:
      position_p_gain: 1000.0
      position_i_gain: 200.0
      position_d_gain: 3.0
      position_i_max: 2000.0
      position_i_min: -2000.0
      max_actuation_force: 10000.0
