uint8 LEFT=1
uint8 RIGHT=2
uint8 STANDARD=0
uint8 SKIP=1
uint8 ROUTE=2
string RED=red
string BLUE=blue
string team
uint8 fake_kfs_decision
uint8 mode
CellIndex[<=12] move_cells
CellIndex[<=12] kfs_cells
---
bool success
string message
uint8 loaded_count
